### ISSUE TITLE
if inv.Series is empty, but inv.Code is not empty, no invoice number is returned

### ISSUE THREAD

**Issue by forwardever** [invopop/gobl.cii#9]
github.com\invopop\gobl.cii@v0.1.0\internal\gtoc\header.go

```
func invoiceNumber(s cbc.Code, c cbc.Code) string {
	if s == "" {
		return s.String()
	}
	return fmt.Sprintf("%s-%s", s, c)
}
```

if inv.Series is empty, but inv.Code is not empty, no invoice number is returned

expected behaviour: return an invoice number if inv.Code is present

**Comment by samlown** [comment]
@forwardever the is fixed in the main branch, we're making a new release now. Thanks for letting us know!

**Comment by forwardever** [comment]
okay, works fine with github main branch, looking forward to the new release
